import { Product } from "@/types/product";

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "1",
    sku: "HW-NISSAN-R34",
    name: "Hot Wheels Nissan Skyline GT-R (BNR34) RLC",
    slug: "hot-wheels-nissan-skyline-gt-r-bnr34-rlc",
    description: "Koleksi langka RLC Spectraflame Blue. Card mint condition, bubble aman, cocok untuk investasi kolektor senior.",
    price: 850000,
    category: "Premium",
    condition: "Blister Card Mint",
    stock: 1,
    status: "available",
    featured: true,
    images: ["https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=800"],
  },
  {
    id: "2",
    sku: "HW-PORSCHE-911",
    name: "Hot Wheels Porsche 911 GT3 RS Euro Speed",
    slug: "hot-wheels-porsche-911-gt3-rs-euro-speed",
    description: "Ban karet (Real Riders), metal body & chassis. Detail lampu dan logo sangat presisi.",
    price: 175000,
    category: "Hot Wheels",
    condition: "New",
    stock: 3,
    status: "available",
    featured: true,
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800"],
  },
  {
    id: "3",
    sku: "HW-LAMBO-INVENTORY",
    name: "Hot Wheels Lamborghini Sesto Elemento Loose",
    slug: "hot-wheels-lamborghini-sesto-elemento-loose",
    description: "Kondisi mulus tanpa card (Loose). Cat tidak ada chip, as roda lurus.",
    price: 45000,
    category: "Loose",
    condition: "Loose Smooth",
    stock: 0,
    status: "sold_out",
    featured: false,
    images: ["https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=800"],
  },
  {
    id: "4",
    sku: "HW-SUPRA-MK4",
    name: "Hot Wheels Toyota Supra Mk4 Boulevard Series",
    slug: "hot-wheels-toyota-supra-mk4-boulevard",
    description: "Series Boulevard ikonik warna kuning. Ban karet Real Riders dengan velg palang 5.",
    price: 240000,
    category: "Premium",
    condition: "New",
    stock: 2,
    status: "available",
    featured: true,
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=800"],
  }
];